In [1]:
import numpy as np

In [4]:
a=np.loadtxt('survey.txt', dtype=int)

In [5]:
a

array([ 7, 10,  5, ...,  5,  9, 10])

In [6]:
len(a)

1167

In [7]:
np.min(a)

1

In [9]:
np.max(a)

10

In [11]:
a.sum()

8461

In [14]:
promoter=a[a>6]
promoter

array([ 7, 10,  9,  9,  7,  9,  9,  9, 10,  9,  9,  7, 10,  9,  7,  9,  9,
        9,  8,  9,  9,  9, 10, 10,  9, 10,  9, 10,  9,  9, 10, 10,  9,  8,
       10,  8,  9, 10,  7, 10, 10,  9,  9, 10, 10, 10,  9, 10,  7,  9, 10,
        9,  9,  7,  9, 10,  9,  9,  9,  9,  9,  9,  8, 10,  8,  7,  9,  9,
        8,  8,  9, 10,  9, 10,  9,  9,  8,  8,  9,  9,  9, 10, 10,  9,  7,
       10,  9,  9, 10,  7,  9,  7,  9, 10,  8,  9,  9,  7,  7,  9,  9,  9,
        7,  8,  9,  9,  7,  9,  9,  9,  8,  9, 10,  8,  9,  9,  9,  9,  7,
        9,  9,  9,  9, 10,  9,  9,  9,  9,  9,  8,  8,  8, 10,  7, 10,  9,
       10,  8, 10, 10,  7,  8,  8, 10,  9, 10,  9,  9,  7,  9,  9,  9,  9,
        9, 10,  9, 10,  8,  9, 10,  9, 10, 10, 10,  7,  9,  9, 10,  8,  7,
       10,  9,  9,  7,  8,  9,  9, 10,  8,  8,  9,  9,  9,  7,  9, 10,  7,
       10,  9,  9,  9,  8, 10,  9,  9,  9,  9,  9, 10,  9,  8,  9,  8,  9,
       10,  9,  7, 10,  7, 10,  9,  9,  7,  8,  9,  9,  7,  7, 10,  9,  8,
       10,  7,  9,  7,  9

In [18]:
detractor=a[a<6]
detractor

array([5, 4, 4, 5, 1, 5, 5, 1, 4, 5, 4, 4, 4, 5, 1, 4, 1, 4, 1, 5, 5, 1,
       1, 4, 1, 5, 4, 1, 1, 4, 1, 5, 1, 4, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1,
       1, 5, 5, 5, 4, 4, 1, 4, 1, 4, 1, 5, 1, 1, 5, 4, 4, 4, 4, 1, 4, 5,
       4, 4, 1, 1, 5, 5, 1, 5, 1, 5, 5, 4, 5, 4, 1, 1, 1, 1, 4, 1, 4, 4,
       5, 4, 1, 1, 1, 1, 5, 4, 5, 5, 4, 1, 5, 1, 4, 4, 1, 1, 1, 4, 4, 5,
       5, 4, 5, 5, 5, 1, 4, 1, 5, 5, 1, 5, 1, 1, 5, 5, 4, 4, 1, 4, 4, 4,
       1, 1, 4, 4, 4, 5, 5, 1, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 5, 4, 4,
       5, 1, 4, 5, 5, 5, 1, 5, 4, 1, 1, 5, 5, 5, 4, 5, 4, 4, 1, 4, 4, 4,
       4, 5, 1, 5, 5, 1, 4, 4, 5, 1, 1, 4, 5, 5, 5, 1, 4, 5, 5, 4, 1, 5,
       5, 5, 1, 1, 5, 5, 1, 1, 1, 4, 5, 5, 4, 4, 4, 5, 1, 4, 1, 4, 5, 4,
       5, 5, 1, 5, 1, 5, 5, 1, 4, 5, 5, 4, 1, 5, 1, 4, 1, 4, 1, 1, 1, 1,
       1, 1, 4, 1, 5, 4, 5, 1, 5, 1, 5, 4, 4, 4, 4, 5, 5, 1, 4, 1, 5, 5,
       1, 4, 1, 1, 4, 4, 4, 4, 1, 4, 1, 1, 4, 1, 5, 4, 1, 1, 5, 4, 5, 4,
       4, 4, 1, 5, 5, 1, 4, 5, 4, 4, 4, 1, 4, 1, 4,

In [25]:
promoter_percentage=len(promoter)/len(a)*100
round(promoter_percentage,2)

71.55

In [26]:
detractor_percentage=len(detractor)/len(a)*100
round(detractor_percentage,2)

28.45