## Numpy - Python library used for working with arrays

#### What is an array?
<p>An array is a data structure that stores a collection of elements, typically of the same data type, in a contiguous block of memory. Arrays can be one-dimensional (like a list), two-dimensional (like a table), or multi-dimensional, and are widely used in programming to handle large datasets and perform mathematical operations efficiently.</p>

<b>Features of Numpy array-</b>
1. Python lists store different types of data so they consume more memory and processing time whereas NumPy arrays are homogeneous and store data in contiguous blocks of memory making access and operations faster.
2. It uses highly optimized C and Fortran libraries under the hood for operations on arrays and matrices.
3. NumPy operations are vectorized. This means that a single operation is applied to an entire array, and the actual calculations happen in optimized C code, speeding up execution.

<b>Install Command - pip install numpy</b>

After installing, import the library

In [197]:
import numpy as np

In [199]:
# creating an array
a = np.array([1,2,3])

In [200]:
a

array([1, 2, 3])

In [202]:
# checking the dimensions of an array
a.ndim

1

In [203]:
a = np.array([[1,2,3],[4,5,6]])

In [205]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [206]:
a.ndim

2

In [208]:
# checking for the shape of an array - (r,c)
a.shape

(2, 3)

In [209]:
# type check 
type(a)

numpy.ndarray

#### Computation Speed 

In [30]:
# normal for loop
%timeit [i**2 for i in range(10000)]

1.24 ms ± 91.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [31]:
%timeit np.array(range(10000))**2

948 µs ± 104 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


#### Array of mixed data types

When NumPy encounters mixed types, it will automatically upcast all elements to the most general type that can represent all the data

In [210]:
np.array(["1",2,6.0,True])

array(['1', '2', '6.0', 'True'], dtype='<U32')

In [211]:
np.array(['a','b','c'])

array(['a', 'b', 'c'], dtype='<U1')

In [37]:
# for inhomogeneous type of data, mention dtype = object
    
x = [[1,3,4,[1,3,5],7,9],[1,3,5,6,[2,3,4],6]]
np.array(x, dtype=object)

array([[1, 3, 4, list([1, 3, 5]), 7, 9],
       [1, 3, 5, 6, list([2, 3, 4]), 6]], dtype=object)

#### Arange Method

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [273]:
np.arange(2,7)

array([2, 3, 4, 5, 6])

In [274]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [276]:
# range(start, end, step(int))
# list(range(1,11,0.5))       # this will raise an error

In [279]:
# arange(start, end, step(float/int))
np.arange(1,11,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

#### Indexing and Slicing

In [280]:
a = np.arange(1,10)

In [281]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [283]:
a[0]

1

In [284]:
a[-1]

9

In [285]:
a[:5]

array([1, 2, 3, 4, 5])

In [286]:
a[6:]

array([7, 8, 9])

#### 2D Array

In [287]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])

In [288]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [290]:
a2[0]

array([1, 2, 3, 4])

In [291]:
# index - way1:
a2[0][0]

1

In [293]:
a2[1][2]

7

In [294]:
# index - way2:
a2[0,0]

1

In [296]:
a2[1,2]

7

In [297]:
# Slicing in 2D array - array[row,column]
a2[:, 1:3]

array([[2, 3],
       [6, 7]])

In [298]:
a2[:,3]

array([4, 8])

#### 3D Array

In [299]:
a3 = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])

In [300]:
a3

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]]])

In [301]:
a3.ndim

3

In [302]:
a3.shape

(2, 2, 3)

In [303]:
# way1 - 
a3[0][1][0]

40

In [304]:
a3[1][0]

array([70, 80, 90])

In [307]:
# way2 -
a3[0,1,0]

40

In [308]:
a3[1,0]

array([70, 80, 90])

In [309]:
a3[0][1][1] = 10000

In [311]:
a3

array([[[   10,    20,    30],
        [   40, 10000,    60]],

       [[   70,    80,    90],
        [  100,   110,   120]]])

In [312]:
# Slicing in 3D array
a3[0, :, :]

array([[   10,    20,    30],
       [   40, 10000,    60]])

In [313]:
a3[1, :, 0]

array([ 70, 100])

#### Reshape Method

reshape() methods converts a 1D array into a 2D array by appropriately specifying the new shape

In [314]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [315]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [317]:
# a.reshape(2,6)       # this will raise an error

reshape(-1) is used to flatten a multi-dimensional array into a 1D array

In [318]:
arr = np.array([[[[1,2,3],[1,2,3],[1,2,3]],[[4,5,6],[4,5,6],[4,5,6]]], [[[1,2,3],[1,2,3],[1,2,3]],[[4,5,6],[4,5,6],[4,5,6]]]])

In [319]:
arr

array([[[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]]])

In [321]:
arr.reshape(-1)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6, 1, 2, 3, 1,
       2, 3, 1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6])

Also, it can be used like this -

In [322]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [141]:
a.reshape(2,-1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [324]:
# a.reshape(3,-1)      # this will raise an error

In [326]:
# a.reshape(-1,-1)     # this will raise an error too

#### Mathematical Operations on Arrays

In [328]:
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [329]:
m+10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [330]:
m-10

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [331]:
m*5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [332]:
m/2

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [333]:
m>4

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [334]:
m<5

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [335]:
m[m<5]

array([0, 1, 2, 3, 4])

In [336]:
m[m>4]

array([5, 6, 7, 8])

In [337]:
m%2==0

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [338]:
m[m%2==0]

array([0, 2, 4, 6, 8])

#### Masking -
Modifying elements of an array based on certain conditions.

In [346]:
mask = m%2==0

In [347]:
m[mask] = 7

In [348]:
m

array([[-1,  1, -1],
       [ 3, -1,  5],
       [-1,  7, -1]])

#### Aggregate Functions

In [349]:
a1 = np.arange(12).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [350]:
# both gives the same result
a1.min(), np.min(a1)         # this is numpy specific

(0, 0)

In [351]:
a1.max()

11

In [352]:
np.max(a1)

11

In [356]:
np.sum(a1)

66

In [357]:
np.mean(a1)

5.5

In [358]:
np.median(a1)

5.5

In [359]:
# ex - 
x = np.array([1,2,3,4,5,10000])
print("Mean of Numpy array: ",np.mean(x))
print("Median of Numpy array: ",np.median(x))

Mean of Numpy array:  1669.1666666666667
Median of Numpy array:  3.5


### nan and None Type -

#### None -
1. In Python, None is used to indicate the absence of a value or a "null" state.
2. None is of type NoneType.
3. In NumPy arrays, using None will automatically convert the array's data type to object.

#### nan -
1. nan stands for "Not a Number".
2. nan was introduced to handle missing or undefined values specifically in the context of numerical computations.
3. It is a floating-point value, so it can only be used with arrays of floating-point type.

In [360]:
type(np.nan), type(None)

(float, NoneType)

In [361]:
x = np.nan
print(x + 5)

nan


In [363]:
x = None
# print(x + 5)    # this will raise an error

In [364]:
a = np.array([1,2,3,4,None])

In [365]:
a.dtype

dtype('O')

In [366]:
b = np.array([1,2,3,4,np.nan])

In [367]:
b.dtype

dtype('float64')

#### Ques. Given an array of marks of students. Display the marks that are greater than the cut-off value.

In [368]:
marks = [34, 67, 90, 55, 49, 88, 70, 22, 64, 95, 83, 47, 76]
marks_array = np.array(marks)
cut_off = 70

In [369]:
marks_array

array([34, 67, 90, 55, 49, 88, 70, 22, 64, 95, 83, 47, 76])

In [370]:
highest_marks = marks_array[marks_array>cut_off]
highest_marks

array([90, 88, 95, 83, 76])

#### np.where
It used to locate the indices of elements in an array that satisfy a given condition

In [248]:
arr = np.array([13,-37, 20, 12, -10, -19, 28, 40, -26, 32])
arr

array([ 13, -37,  20,  12, -10, -19,  28,  40, -26,  32])

In [249]:
np.where(arr<0)

(array([1, 4, 5, 8], dtype=int64),)

In [250]:
np.where(arr<20)

(array([0, 1, 3, 4, 5, 8], dtype=int64),)

Also, np.where can be used with additional parameters to act more like a conditional replacement operation.<br>
np.where(condn, truevalue, falsevalue)

In [251]:
np.where(arr<0, '-ve', '+ve')

array(['+ve', '-ve', '+ve', '+ve', '-ve', '-ve', '+ve', '+ve', '-ve',
       '+ve'], dtype='<U3')

In [252]:
np.where(arr<0, 0, arr)

array([13,  0, 20, 12,  0,  0, 28, 40,  0, 32])

#### Ques. Given an array, return the indices of the numbers that are divisible by 5

In [258]:
arr = np.array([4, 19, 15, 31, 40, 26, 35, 5, 18, 43, 10])
arr

array([ 4, 19, 15, 31, 40, 26, 35,  5, 18, 43, 10])

In [259]:
np.where(arr%5==0)

(array([ 2,  4,  6,  7, 10], dtype=int64),)

If not providing condition, it returns the index of all non-zero numbers

In [263]:
arr2 = np.array([2,3,0,8,0,9,1,4,5,0,7])
np.where(arr2)

(array([ 0,  1,  3,  5,  6,  7,  8, 10], dtype=int64),)

#### Loading a file into numpy

In [270]:
survey_score = np.loadtxt('survey.txt', dtype='int')

In [271]:
survey_score

array([ 7, 10,  5, ...,  5,  9, 10])

#### Ques.
1. Does the loaded file returns an array of survey score?
2. Find the length of the returned array.
3. Perform aggregate operations - min, max, sum
4. Let Survey score greater than 6 is known as promoter score. Display the promoter score.
5. Let Survey score less than 6 is known as detractor score. Display the detractor score.
6. Calculate the promoter and detractor percentage.