In [94]:
import numpy as np

#### Sorting a numpy array

In [95]:
a = np.array([23, 65, 10, 45, 2, 17, 38, 19, 44, 26])

In [96]:
a

array([23, 65, 10, 45,  2, 17, 38, 19, 44, 26])

In [97]:
np.sort(a)           # this does not make a permanent change

array([ 2, 10, 17, 19, 23, 26, 38, 44, 45, 65])

In [22]:
a

array([23, 65, 10, 45,  2, 17, 38, 19, 44, 26])

In [98]:
a.sort()            # this will make a permanent change

In [99]:
a

array([ 2, 10, 17, 19, 23, 26, 38, 44, 45, 65])

#### argsort - argument sort
array.argsort() returns the indices of sorted elements within an array

In [100]:
a = np.array([12, 16, 9, 1, 30])
a

array([12, 16,  9,  1, 30])

In [101]:
np.argsort(a)

array([3, 2, 0, 1, 4], dtype=int64)

In [48]:
np.argmax(a)

4

In [49]:
np.argmin(a)

3

Sorting a 2D array

In [52]:
x = np.array([[20,4,8],[12,2,10]])
x

array([[20,  4,  8],
       [12,  2, 10]])

In [54]:
# by default it sorts the array row wise
np.sort(x)

array([[ 4,  8, 20],
       [ 2, 10, 12]])

In [56]:
# sort a 2D array column wise
np.sort(x, axis=0)

array([[12,  2,  8],
       [20,  4, 10]])

In numpy,
1. axis = 0 --> column
2. axis = 1 --> row

In [120]:
 # axis=None removes the shape and convert the matrix into a 1D array
np.sort(x, axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Multiplication of two arrays

In [106]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
y = np.arange(11,20).reshape(3,3)
y

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [108]:
x*y

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

#### Matrix Multiplication

In [109]:
a = np.array([[1,2,3],[3,4,5]])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [110]:
b = np.array([[11,12],[13,14],[15,16]])
b

array([[11, 12],
       [13, 14],
       [15, 16]])

In [111]:
a.shape

(2, 3)

In [112]:
b.shape

(3, 2)

In [113]:
# 1. using matmul method -
np.matmul(a,b)

array([[ 82,  88],
       [160, 172]])

In [114]:
# 2. short way for matrix multiplication using @
a@b

array([[ 82,  88],
       [160, 172]])

Since matrix is nothing but a vector, hence we can find the dot product between the two matrices.

In [115]:
# 3. using np.dot
# this will give same result as matrix multiplication
np.dot(a,b)

array([[ 82,  88],
       [160, 172]])

In [116]:
# 4. matrix1.dot(matrix2)
a.dot(b)

array([[ 82,  88],
       [160, 172]])

#### Scaler Multiplication - multiplying a vector with a scaler value

In [117]:
a = np.arange(1,10).reshape(3,3)

In [118]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
a*6

array([[ 6, 12, 18],
       [24, 30, 36],
       [42, 48, 54]])

In [140]:
np.dot(a,6)

array([[ 6, 12, 18],
       [24, 30, 36],
       [42, 48, 54]])

#### Vectorization
Vectorization is a method of performing array operations without the use of for loops.

In [120]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

Ex-1

In [121]:
def even(n):
    return n%2==0

In [122]:
Even_num = np.vectorize(even)

In [123]:
Even_num(arr)

array([False,  True, False,  True, False])

In [124]:
Even_num(np.array([3,4,5,6,7,8,9]))

array([False,  True, False,  True, False,  True, False])

Ex-2

In [134]:
even_odd = np.vectorize(lambda x:'even' if x%2 == 0 else 'odd')

In [135]:
even_odd(arr)

array(['odd', 'even', 'odd', 'even', 'odd'], dtype='<U4')

Ex-3

In [136]:
import math

In [138]:
Power = np.vectorize(math.pow)

In [139]:
Power(arr,3)

array([  1.,   8.,  27.,  64., 125.])

Ex-4

In [168]:
Fact = np.vectorize(math.factorial)

In [169]:
Fact(arr)

array([  1,   2,   6,  24, 120])

Ex-5

In [170]:
logarithm = np.vectorize(math.log)

In [171]:
logarithm(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

#### Ques. Find which of the elements of an array are prime.
array = np.array([12, 4, 11, 16, 3, 20, 17, 13, 8])
1. Return prime if the number is prime
2. Return not prime if the number is not prime

#### Tile Function
It used to repeat multiple rows and columns.<br>np.tile(no. of times rows need to repeat, no. of times columns need to repeat)

In [142]:
arr = np.arange(10,40,10)

In [144]:
arr

array([10, 20, 30])

In [150]:
np.tile(arr,(4,2))

array([[10, 20, 30, 10, 20, 30],
       [10, 20, 30, 10, 20, 30],
       [10, 20, 30, 10, 20, 30],
       [10, 20, 30, 10, 20, 30]])

In [151]:
np.tile(arr,(3,1))

array([[10, 20, 30],
       [10, 20, 30],
       [10, 20, 30]])

#### Broadcasting
A process that allows arrays with different shapes to be used in arithmetic operations.<br>
It stretches or replicate smaller arrays to match the dimensions of larger ones during these operations.

In [153]:
a = np.arange(1,13).reshape(-1,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [154]:
b = np.array([8, 1, 6])

In [155]:
b

array([8, 1, 6])

In [157]:
a*b

array([[ 8,  2, 18],
       [32,  5, 36],
       [56,  8, 54],
       [80, 11, 72]])

Here array b is broadcasted<br>
np.tile() function do broadcasting as it repeats rows or columns many times

In [158]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [159]:
b = np.arange(5,9).reshape(4,1)
b

array([[5],
       [6],
       [7],
       [8]])

In [161]:
a+b

array([[ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12]])

a has shape 1x4 and b has shape 4x1 then a+b will have shape (any mathematical operation) 4x4 as both a and b are broadcasted.

In [163]:
a = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [164]:
b = np.arange(16).reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [165]:
a+b

ValueError: operands could not be broadcast together with shapes (2,4) (4,4) 

Broadcasting is done only if one of the array is 1D

#### Shallow Copy and Deep Copy

In [167]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [170]:
y = x[:3]
y

array([1, 2, 3])

In [171]:
y[0]=100
y

array([100,   2,   3])

In [172]:
x

array([100,   2,   3,   4,   5])

Making changes in array x changes the element in array y too. This is known as shallow copy.

np.shares_memory(array1, array2) is used to check whether the arrays share same memory location or not

In [173]:
np.shares_memory(x,y)

True

Therefore, it can seen that <b>slicing creates a shallow copy</b>

In [175]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [176]:
b = a+10
b

array([11, 12, 13, 14, 15])

In [177]:
a[0] = 9999
a

array([9999,    2,    3,    4,    5])

In [178]:
b

array([11, 12, 13, 14, 15])

In [179]:
np.shares_memory(a,b)

False

This is a deep copy.<br>
Therefore, it can be seen that creating an array on performing mathematical operations creates a deep copy

In [181]:
# ex - 
a1 = np.arange(0,4)
a1

array([0, 1, 2, 3])

In [182]:
b1 = a1+0
b1

array([0, 1, 2, 3])

In [183]:
np.shares_memory(a1,b1)

False

If all the elements are same, it does not mean that it is a shallow copy. It can be a deep copy.

For specifically creating a deep copy, we use .copy() method

In [184]:
x2 = np.array([5,6,7])
x2

array([5, 6, 7])

In [185]:
y2 = x2.copy()
y2

array([5, 6, 7])

In [186]:
np.shares_memory(x2, y2)

False

In [187]:
y2[0] = 1000
y2

array([1000,    6,    7])

In [188]:
x2

array([5, 6, 7])

Limitation of .copy() - It creates a deep copy but not with object data type

In [189]:
X = np.array([1.2, 2, 3.0, 'a', [2,3,4]], dtype='object')
X

array([1.2, 2, 3.0, 'a', list([2, 3, 4])], dtype=object)

In [190]:
Y = X.copy()
Y

array([1.2, 2, 3.0, 'a', list([2, 3, 4])], dtype=object)

In [191]:
X[4][0] = 10000
X

array([1.2, 2, 3.0, 'a', list([10000, 3, 4])], dtype=object)

In [192]:
Y

array([1.2, 2, 3.0, 'a', list([10000, 3, 4])], dtype=object)

In [193]:
np.shares_memory(X,Y)

False

1. In shallow copy, array structure is copied but not the objects (like lists) inside the array.<br>
2. A deep copy would copy both the array structure and the objects inside it.<br>
3. In the above case, since the outer structure is copied, hence np.shares_memory is returning false<br>
4. np.shares_memory() only checks if the arrays themselves are in the same memory, not the individual objects inside them.

For creating a deep copy with object data type use deepcopy method -

In [194]:
from copy import deepcopy
Y = deepcopy(X)

In [195]:
X

array([1.2, 2, 3.0, 'a', list([10000, 3, 4])], dtype=object)

In [196]:
Y

array([1.2, 2, 3.0, 'a', list([10000, 3, 4])], dtype=object)

In [198]:
X[4][0] = 11111
X

array([1.2, 2, 3.0, 'a', list([11111, 3, 4])], dtype=object)

In [199]:
Y

array([1.2, 2, 3.0, 'a', list([10000, 3, 4])], dtype=object)

#### View Function
It creates a shallow copy

In [200]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [201]:
b = a.view()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [202]:
b[0] = 1000
b

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [203]:
a

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])