In [31]:
import numpy as np

#### Splitting the data in Numpy

In [32]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
np.split(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [36]:
b = np.arange(14)
# b.split(b,3)        # this will raise an error as splitting cannot be done with unequal size

For splitting an array into unequal parts, use list of index

In [37]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [38]:
np.split(b, [3,11])

[array([0, 1, 2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10]),
 array([11, 12, 13])]

In [8]:
np.split(b, [3,7,12,14])

[array([0, 1, 2]),
 array([3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11]),
 array([12, 13]),
 array([], dtype=int32)]

As we can see here the last index was not present in the list, hence it returns an empty array

1. if we split an array into 2 parts it will return 3 arrays
2. if we split an array into 3 parts it will return 4 arrays
3. if we split an array into 4 parts it will return 5 arrays and so on.........

#### Horizontal and Vertical Splits

In [40]:
x = np.arange(24).reshape(4,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

hsplit - splits the array on horizontal axis

In [10]:
np.hsplit(x,2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [41]:
np.hsplit(x,3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])]

In [43]:
# np.hsplit(x,4)        # this will raise an error

For unequal division, here also we will use list of indices

In [47]:
np.hsplit(x,[2,3,8])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]]),
 array([[ 2],
        [ 8],
        [14],
        [20]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]]),
 array([], shape=(4, 0), dtype=int32)]

vsplit - splits the array on vertical axis

In [49]:
x = np.arange(20).reshape(-1,2)
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [50]:
np.vsplit(x,2)

[array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]])]

In [51]:
# np.vsplit(x,3)       # this will raise an error

In [52]:
np.vsplit(x,5)

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]]),
 array([[ 8,  9],
        [10, 11]]),
 array([[12, 13],
        [14, 15]]),
 array([[16, 17],
        [18, 19]])]

In [53]:
np.vsplit(x, [2,4,6,9,12])

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]]),
 array([[ 8,  9],
        [10, 11]]),
 array([[12, 13],
        [14, 15],
        [16, 17]]),
 array([[18, 19]]),
 array([], shape=(0, 2), dtype=int32)]

#### Stacking

In [54]:
array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [55]:
array2 = np.array([5,6,7,8,9])
array2

array([5, 6, 7, 8, 9])

hstack - combine/stack two arrays sideways

In [56]:
np.hstack([array1,array2])

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

vstcak - combine/stack two arrays one below the other

In [57]:
np.vstack([array1,array2])

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

1. If there are equal number of rows then hstack is applied
2. If there are equal number of columns then vstack is applied

In [58]:
m = np.arange(1,4)
m

array([1, 2, 3])

In [59]:
n = np.arange(0,2)
n

array([0, 1])

In [60]:
o = np.arange(1,8)
o

array([1, 2, 3, 4, 5, 6, 7])

In [64]:
np.hstack([m,n,o])

array([1, 2, 3, 0, 1, 1, 2, 3, 4, 5, 6, 7])

In [66]:
q = np.arange(12).reshape(-1,3)
q

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [67]:
m

array([1, 2, 3])

In [69]:
np.vstack([m,q])

array([[ 1,  2,  3],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [71]:
np.vstack([m,q,q,q,])

array([[ 1,  2,  3],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### np.concatenate() 
It is used to apply both type of stacking together using a single line code.<br>
But is applied when both arrays have same dimension

In [72]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [73]:
b = np.arange(8).reshape(2,4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [75]:
np.hstack([a,b])

array([[0, 1, 0, 1, 2, 3],
       [2, 3, 4, 5, 6, 7]])

In [79]:
np.concatenate([b,a], axis=1)

array([[0, 1, 2, 3, 0, 1],
       [4, 5, 6, 7, 2, 3]])

we are getting the same result using both of the above methods

In [81]:
# axis = None
# it combines the two arrays like hstack

np.concatenate([a,b], axis=None)

array([0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 7])

if we do not provide any axis then its default axis is set to 0 (i.e.; hstack)
provided both the arrays are of same shape

#### np.random

np.random.randint - Generate a number between a given range

In [94]:
np.random.randint(100)

4

In [95]:
np.random.randint(51,100)

67

np.random.choice - It allows us to generate a random value based on an array of values

In [99]:
np.random.choice([2,3,4])

4

np.random.rand - Generate a 2-D array with n rows and m columns having numbers between 0 and 1<br>
np.random.rand(n,m)

In [100]:
np.random.rand(3,5)

array([[0.69698782, 0.5281502 , 0.24189527, 0.38891676, 0.07394008],
       [0.23872002, 0.47049274, 0.82118944, 0.03172456, 0.271468  ],
       [0.38339713, 0.15609462, 0.44995572, 0.009421  , 0.60282735]])

In [104]:
np.random.rand(4,8)

array([[0.82646459, 0.68509323, 0.81685772, 0.05133049, 0.70795149,
        0.7475868 , 0.5899245 , 0.69014959],
       [0.84268506, 0.22350573, 0.53452515, 0.45793843, 0.35663126,
        0.6219489 , 0.88744306, 0.22858043],
       [0.71097146, 0.71609517, 0.22965973, 0.59082496, 0.27097193,
        0.73743868, 0.70748802, 0.97323194],
       [0.9378105 , 0.78501086, 0.6999596 , 0.36201257, 0.1448169 ,
        0.87240932, 0.83558619, 0.90020931]])

#### np.linspace

In [105]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [106]:
np.linspace(-1,1,100)

array([-1.        , -0.97979798, -0.95959596, -0.93939394, -0.91919192,
       -0.8989899 , -0.87878788, -0.85858586, -0.83838384, -0.81818182,
       -0.7979798 , -0.77777778, -0.75757576, -0.73737374, -0.71717172,
       -0.6969697 , -0.67676768, -0.65656566, -0.63636364, -0.61616162,
       -0.5959596 , -0.57575758, -0.55555556, -0.53535354, -0.51515152,
       -0.49494949, -0.47474747, -0.45454545, -0.43434343, -0.41414141,
       -0.39393939, -0.37373737, -0.35353535, -0.33333333, -0.31313131,
       -0.29292929, -0.27272727, -0.25252525, -0.23232323, -0.21212121,
       -0.19191919, -0.17171717, -0.15151515, -0.13131313, -0.11111111,
       -0.09090909, -0.07070707, -0.05050505, -0.03030303, -0.01010101,
        0.01010101,  0.03030303,  0.05050505,  0.07070707,  0.09090909,
        0.11111111,  0.13131313,  0.15151515,  0.17171717,  0.19191919,
        0.21212121,  0.23232323,  0.25252525,  0.27272727,  0.29292929,
        0.31313131,  0.33333333,  0.35353535,  0.37373737,  0.39